### ISSUE TITLE
bun shows set of OK tests' results if started in a directory without a bundle 

### ISSUE THREAD

**Issue by vavy** [adyatlov/bun#36]
Example:

[root@c7srv 1]# pwd
/tmp/1
[root@c7srv 1]# ls -la
total 8
drwxr-xr-x.  2 root root 4096 May 29 11:12 .
drwxrwxrwt. 17 root root 4096 May 29 11:12 ..
[root@c7srv 1]#
[root@c7srv 1]# bun
[OK] "dcos-version" - All versions are the same: .
[OK] "diagnostics-health" - No problems were found.
[OK] "disk-space-exhibitor" - No problems were found.
[OK] "marathon-deployments" - No problems were found.
[OK] "mesos-actor-mailboxes" - All Mesos actors are fine.
[PROBLEM] "node-count" - Number of masters is not valid. Masters: 0, Agents: 0, Public Agents: 0, Total: 0
---------------
Problem details
---------------
It should be 1, 3 or 5 masters.
[OK] "unmount-volume" - No problems were found.
[root@c7srv 1]#

**Comment by adyatlov** [comment]
Fixed
